import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";
import {CustomerProvider} from '@/app/context/CustomerContext'
const inter = Inter({ subsets: ['latin'] })
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

export const metadata = {
  title: 'Customer Management App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomerProvider>
        
        <div className="flex justify-between items-center p-6 shadow bg-gray-800 text-white">
        <div className="font-medium text-xl">
          <Link href="/">Customer Management</Link>
        </div>
        <div>
          <Link href="/add-customer">
            <button className="text-xs font-medium shadow-md px-3 py-2 rounded bg-blue-500 hover:bg-blue-600 transition-all duration-200 ease-in-out text-white">
              Add Customer
            </button>
          </Link>
        </div>
      </div>
        {children}
      
        </CustomerProvider>
        <ToastContainer />     
        </body>
    </html>
  )
}
